### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by Sergio-Soria** [r57zone/Firewall-Easy#2]
I send you the translation into Spanish, as a minimal contribution to the project.
Regards
[Spanish.zip](https://github.com/r57zone/Firewall-Easy/files/8880950/Spanish.zip)

**Comment by Sergio-Soria** [comment]
updated
[Spanish.zip](https://github.com/r57zone/Firewall-Easy/files/8880988/Spanish.zip)

**Comment by r57zone** [comment]
Hi, thanks, i will add it

**Comment by r57zone** [comment]
Updated the archive with the program, now it should run in Spanish by default, on Spanish Windows.
